# Generated by Django 6.1.1 on 2026-09-30 13:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías de Maquinaria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('EMPRESA_CONSTRUCTORA', 'Empresa Constructora'), ('EJECUTIVO_ARRIENDOS', 'Ejecutivo de Arriendos')], default='EMPRESA_CONSTRUCTORA', help_text='Define los permisos del usuario (Cliente Constructora o Gestor Ejecutivo)', max_length=30, verbose_name='Rol en el Sistema')),
                ('rut_empresa', models.CharField(blank=True, help_text='Ejemplo: 76.123.456-K', max_length=20, null=True, verbose_name='RUT Empresa / Persona')),
                ('razon_social', models.CharField(blank=True, help_text='Nombre de la empresa constructora o institución', max_length=150, null=True, verbose_name='Razón Social / Empresa')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios del Sistema',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarroArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario')),
            ],
            options={
                'verbose_name': 'Carro de Arriendo',
                'verbose_name_plural': 'Carros de Arriendo',
            },
        ),
        migrations.CreateModel(
            name='ContratoArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADO', 'PAGADO'), ('ENTREGADO', 'ENTREGADO'), ('COMPLETADO', 'COMPLETADO'), ('CANCELADO', 'CANCELADO')], default='PENDIENTE', max_length=20, verbose_name='Estado del Contrato')),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto Total Contratado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente (Empresa Constructora)')),
            ],
            options={
                'verbose_name': 'Contrato de Arriendo',
                'verbose_name_plural': 'Contratos de Arriendo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Maquinaria')),
                ('descripcion', models.TextField(verbose_name='Descripción y Especificaciones Técnicas')),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tarifa Diaria (CLP/USD)')),
                ('garantia_fija', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Garantía Fija Obligatoria')),
                ('unidades_disponibles', models.PositiveIntegerField(default=1, verbose_name='Unidades Disponibles en Flota (Stock)')),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen del Equipo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinarias', to='api.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias de Construcción',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio del Arriendo')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Término del Arriendo')),
                ('dias_uso', models.PositiveIntegerField(editable=False, verbose_name='Días de Uso Estimados')),
                ('costo_calculado', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Costo Calculado (Tarifa + Garantía)')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.carroarriendo', verbose_name='Carro Asociado')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carros', to='api.maquinaria', verbose_name='Maquinaria Seleccionada')),
            ],
            options={
                'verbose_name': 'Ítem de Carro',
                'verbose_name_plural': 'Ítems de Carro',
            },
        ),
        migrations.CreateModel(
            name='DetalleContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maquinaria', models.CharField(max_length=150, verbose_name='Nombre del Equipo (Histórico)')),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tarifa Diaria Congelada')),
                ('garantia_fija', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Garantía Fija Congelada')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio Pactada')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin Pactada')),
                ('dias_uso', models.PositiveIntegerField(verbose_name='Días de Uso Facturados')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal Facturado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.contratoarriendo', verbose_name='Contrato Asociado')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_historicos', to='api.maquinaria', verbose_name='Maquinaria de Referencia')),
            ],
            options={
                'verbose_name': 'Detalle de Contrato',
                'verbose_name_plural': 'Detalles de Contrato',
            },
        ),
    ]
