# Generated by Django 6.1.1 on 2026-09-30 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoarriendo',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico (Invitado)'),
        ),
        migrations.AddField(
            model_name='contratoarriendo',
            name='es_invitado',
            field=models.BooleanField(default=False, verbose_name='¿Es Arriendo de Invitado (Sin Registro)?'),
        ),
        migrations.AddField(
            model_name='contratoarriendo',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre o Razón Social (Invitado)'),
        ),
        migrations.AddField(
            model_name='contratoarriendo',
            name='rut_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT Empresa / Persona (Invitado)'),
        ),
        migrations.AddField(
            model_name='contratoarriendo',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono de Contacto (Invitado)'),
        ),
        migrations.AlterField(
            model_name='contratoarriendo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Registrado'),
        ),
    ]
